LittlerootTown_BrendansHouse_2F_MapScripts::
	map_script MAP_SCRIPT_ON_TRANSITION, LittlerootTown_BrendansHouse_2F_OnTransition
	map_script MAP_SCRIPT_ON_WARP_INTO_MAP_TABLE, LittlerootTown_BrendansHouse_2F_OnWarp
	.byte 0

LittlerootTown_BrendansHouse_2F_OnTransition:
	call_if_unset FLAG_GAVE_STARTER_EEVEE, LittlerootTown_BrendansHouse_2F_EventScript_GiveEevee
	call_if_lt VAR_LITTLEROOT_RIVAL_STATE, 2, LittlerootTown_BrendansHouse_2F_EventScript_CheckSetReadyToMeetBrendan
	call_if_ge VAR_LITTLEROOT_RIVAL_STATE, 3, LittlerootTown_BrendansHouse_2F_EventScript_CheckShouldUpdateBrendanPos
	call_if_eq VAR_LITTLEROOT_INTRO_STATE, 4, PlayersHouse_2F_EventScript_BlockStairsUntilClockIsSet
	call SecretBase_EventScript_SetDecorationFlags
	setvar VAR_SECRET_BASE_INITIALIZED, 0
	end

LittlerootTown_BrendansHouse_2F_EventScript_CheckShouldUpdateBrendanPos::
	goto_if_set FLAG_MET_RIVAL_LILYCOVE, LittlerootTown_BrendansHouse_2F_EventScript_TryUpdateBrendanPos
	goto_if_ge VAR_BIRCH_LAB_STATE, 2, LittlerootTown_BrendansHouse_2F_EventScript_Ret
	goto LittlerootTown_BrendansHouse_2F_EventScript_TryUpdateBrendanPos

LittlerootTown_BrendansHouse_2F_EventScript_TryUpdateBrendanPos::
	checkplayergender
	goto_if_eq VAR_RESULT, MALE, LittlerootTown_BrendansHouse_2F_EventScript_Ret
	@ Odd that the MaysHouse equivalent was used below instead
	goto_if_ge VAR_DEX_UPGRADE_JOHTO_STARTER_STATE, 2, LittlerootTown_MaysHouse_2F_EventScript_Ret
	setobjectxyperm LOCALID_RIVALS_HOUSE_2F_RIVAL, 0, 2
	setobjectmovementtype LOCALID_RIVALS_HOUSE_2F_RIVAL, MOVEMENT_TYPE_FACE_UP
	return

LittlerootTown_BrendansHouse_2F_EventScript_Ret::
	return

LittlerootTown_BrendansHouse_2F_EventScript_CheckSetReadyToMeetBrendan::
	checkplayergender
	goto_if_eq VAR_RESULT, FEMALE, LittlerootTown_BrendansHouse_2F_EventScript_SetReadyToMeetBrendan
	return

LittlerootTown_BrendansHouse_2F_EventScript_SetReadyToMeetBrendan::
	setvar VAR_LITTLEROOT_RIVAL_STATE, 2
	return

LittlerootTown_BrendansHouse_2F_EventScript_GiveEevee::
    setflag FLAG_SYS_POKEMON_GET
	givemon SPECIES_EEVEE, 15
	compare VAR_RESULT, MON_CANT_GIVE
	goto_if_eq LittlerootTown_BrendansHouse_2F_EventScript_GiveEevee_End
	setflag FLAG_GAVE_STARTER_EEVEE
LittlerootTown_BrendansHouse_2F_EventScript_GiveEevee_End::
	return

LittlerootTown_BrendansHouse_2F_OnWarp:
	map_script_2 VAR_SECRET_BASE_INITIALIZED, 0, LittlerootTown_BrendansHouse_2F_EventScript_CheckInitDecor
	.2byte 0

LittlerootTown_BrendansHouse_2F_EventScript_CheckInitDecor::
	checkplayergender
	goto_if_eq VAR_RESULT, MALE, SecretBase_EventScript_InitDecorations
	end

LittlerootTown_BrendansHouse_2F_EventScript_RivalsPokeBall::
	lockall
	goto_if_eq VAR_LITTLEROOT_RIVAL_STATE, 2, LittlerootTown_BrendansHouse_2F_EventScript_MeetBrendan
	msgbox RivalsHouse_2F_Text_ItsRivalsPokeBall, MSGBOX_DEFAULT
	releaseall
	end

LittlerootTown_BrendansHouse_2F_EventScript_MeetBrendan::
	delay 10
	addobject LOCALID_RIVALS_HOUSE_2F_RIVAL
	applymovement LOCALID_RIVALS_HOUSE_2F_RIVAL, LittlerootTown_BrendansHouse_2F_Movement_BrendanEnters
	waitmovement 0
	playse SE_PIN
	applymovement LOCALID_RIVALS_HOUSE_2F_RIVAL, Common_Movement_ExclamationMark
	waitmovement 0
	applymovement LOCALID_RIVALS_HOUSE_2F_RIVAL, Common_Movement_Delay48
	waitmovement 0
	delay 10
	playbgm MUS_ENCOUNTER_BRENDAN, TRUE
	call_if_eq VAR_FACING, DIR_NORTH, LittlerootTown_BrendansHouse_2F_EventScript_MeetBrendanNorth
	call_if_eq VAR_FACING, DIR_SOUTH, LittlerootTown_BrendansHouse_2F_EventScript_MeetBrendanSouth
	call_if_eq VAR_FACING, DIR_WEST, LittlerootTown_BrendansHouse_2F_EventScript_MeetBrendanWest
	call_if_eq VAR_FACING, DIR_EAST, LittlerootTown_BrendansHouse_2F_EventScript_MeetBrendanEast
	setvar VAR_LITTLEROOT_RIVAL_STATE, 3
	setflag FLAG_HIDE_LITTLEROOT_TOWN_BRENDANS_HOUSE_2F_POKE_BALL
	clearflag FLAG_HIDE_LITTLEROOT_TOWN_BRENDANS_HOUSE_RIVAL_BEDROOM
	setvar VAR_LITTLEROOT_TOWN_STATE, 1
	savebgm MUS_DUMMY
	fadedefaultbgm
	releaseall
	end

LittlerootTown_BrendansHouse_2F_EventScript_MeetBrendanNorth::
	applymovement LOCALID_RIVALS_HOUSE_2F_RIVAL, LittlerootTown_BrendansHouse_2F_Movement_BrendanApproachPlayerNorth
	waitmovement 0
	applymovement LOCALID_PLAYER, Common_Movement_WalkInPlaceFasterRight
	waitmovement 0
	msgbox RivalsHouse_2F_Text_BrendanWhoAreYou, MSGBOX_DEFAULT
	closemessage
	applymovement LOCALID_PLAYER, LittlerootTown_BrendansHouse_2F_Movement_PlayerWatchBrendanNorth
	applymovement LOCALID_RIVALS_HOUSE_2F_RIVAL, LittlerootTown_BrendansHouse_2F_Movement_BrendanWalkToPCNorth
	waitmovement 0
	return

LittlerootTown_BrendansHouse_2F_EventScript_MeetBrendanSouth::
	applymovement LOCALID_RIVALS_HOUSE_2F_RIVAL, LittlerootTown_BrendansHouse_2F_Movement_BrendanApproachPlayerSouth
	waitmovement 0
	applymovement LOCALID_PLAYER, Common_Movement_WalkInPlaceFasterRight
	waitmovement 0
	msgbox RivalsHouse_2F_Text_BrendanWhoAreYou, MSGBOX_DEFAULT
	closemessage
	applymovement LOCALID_PLAYER, LittlerootTown_BrendansHouse_2F_Movement_PlayerWatchBrendanSouth
	applymovement LOCALID_RIVALS_HOUSE_2F_RIVAL, LittlerootTown_BrendansHouse_2F_Movement_BrendanWalkToPCSouth
	waitmovement 0
	return

LittlerootTown_BrendansHouse_2F_EventScript_MeetBrendanWest::
	applymovement LOCALID_RIVALS_HOUSE_2F_RIVAL, LittlerootTown_BrendansHouse_2F_Movement_BrendanApproachPlayerWest
	waitmovement 0
	applymovement LOCALID_PLAYER, Common_Movement_WalkInPlaceFasterRight
	waitmovement 0
	msgbox RivalsHouse_2F_Text_BrendanWhoAreYou, MSGBOX_DEFAULT
	closemessage
	applymovement LOCALID_PLAYER, LittlerootTown_BrendansHouse_2F_Movement_PlayerWatchBrendanWest
	applymovement LOCALID_RIVALS_HOUSE_2F_RIVAL, LittlerootTown_BrendansHouse_2F_Movement_BrendanWalkToPCWest
	waitmovement 0
	return

LittlerootTown_BrendansHouse_2F_EventScript_MeetBrendanEast::
	applymovement LOCALID_RIVALS_HOUSE_2F_RIVAL, LittlerootTown_BrendansHouse_2F_Movement_BrendanApproachPlayerEast
	waitmovement 0
	applymovement LOCALID_PLAYER, Common_Movement_WalkInPlaceFasterUp
	waitmovement 0
	msgbox RivalsHouse_2F_Text_BrendanWhoAreYou, MSGBOX_DEFAULT
	closemessage
	applymovement LOCALID_RIVALS_HOUSE_2F_RIVAL, LittlerootTown_BrendansHouse_2F_Movement_BrendanWalkToPCEast
	waitmovement 0
	return

LittlerootTown_BrendansHouse_2F_Movement_BrendanEnters:
	walk_down
	walk_down
	walk_in_place_faster_left
	step_end

LittlerootTown_BrendansHouse_2F_Movement_BrendanApproachPlayerNorth:
	walk_left
	walk_left
	walk_down
	walk_down
	walk_left
	step_end

LittlerootTown_BrendansHouse_2F_Movement_BrendanWalkToPCNorth:
	walk_up
	walk_up
	walk_up
	walk_left
	walk_left
	walk_left
	walk_left
	walk_in_place_faster_up
	step_end

LittlerootTown_BrendansHouse_2F_Movement_PlayerWatchBrendanNorth:
	delay_16
	walk_in_place_faster_up
	delay_16
	delay_16
	delay_16
	delay_16
	walk_in_place_faster_left
	step_end

LittlerootTown_BrendansHouse_2F_Movement_BrendanApproachPlayerSouth:
	walk_left
	walk_left
	walk_left
	step_end

LittlerootTown_BrendansHouse_2F_Movement_BrendanWalkToPCSouth:
	walk_up
	walk_left
	walk_left
	walk_left
	walk_left
	walk_in_place_faster_up
	step_end

LittlerootTown_BrendansHouse_2F_Movement_PlayerWatchBrendanSouth:
	delay_16
	walk_in_place_faster_up
	delay_16
	delay_16
	walk_in_place_faster_left
	step_end

LittlerootTown_BrendansHouse_2F_Movement_BrendanApproachPlayerWest:
	walk_left
	walk_left
	walk_down
	walk_in_place_faster_left
	step_end

LittlerootTown_BrendansHouse_2F_Movement_BrendanWalkToPCWest:
	walk_up
	walk_up
	walk_left
	walk_left
	walk_left
	walk_left
	walk_left
	walk_in_place_faster_up
	step_end

LittlerootTown_BrendansHouse_2F_Movement_PlayerWatchBrendanWest:
	delay_8
	delay_16
	walk_in_place_faster_up
	delay_16
	delay_16
	walk_in_place_faster_left
	step_end

LittlerootTown_BrendansHouse_2F_Movement_BrendanApproachPlayerEast:
	walk_left
	walk_left
	walk_left
	walk_left
	walk_left
	walk_in_place_faster_down
	step_end

LittlerootTown_BrendansHouse_2F_Movement_BrendanWalkToPCEast:
	walk_up
	walk_left
	walk_left
	walk_in_place_faster_up
	step_end

@ Unused, the player is already facing this direction so its unneeded
LittlerootTown_BrendansHouse_2F_Movement_PlayerWatchBrendanEast:
	delay_16
	delay_16
	walk_in_place_faster_left
	step_end

LittlerootTown_BrendansHouse_2F_EventScript_PC::
	lockall
	checkplayergender
	goto_if_eq VAR_RESULT, MALE, LittlerootTown_BrendansHouse_2F_EventScript_CheckPlayersPC
	goto_if_eq VAR_RESULT, FEMALE, LittlerootTown_BrendansHouse_2F_EventScript_CheckRivalsPC
	end

LittlerootTown_BrendansHouse_2F_EventScript_CheckPlayersPC::
	setvar VAR_0x8004, PC_LOCATION_BRENDANS_HOUSE
	special DoPCTurnOnEffect
	playse SE_PC_ON
	goto PlayersHouse_2F_EventScript_PaletteCustomization

PlayersHouse_2F_EventScript_PaletteCustomization::
	msgbox LittlerootTown_BrendansHouse_2F_Text_PaletteChoice, MSGBOX_YESNO
	goto_if_eq VAR_RESULT, NO, PlayersHouse_2F_EventScript_PCTurnOn
	call PlayersHouse_2F_EventScript_ShowPaletteMenu
	goto PlayersHouse_2F_EventScript_PCTurnOn

PlayersHouse_2F_EventScript_DefaultPalette::
	setvar VAR_PLAYER_PALETTE_CHOICE, 0
	goto PlayersHouse_2F_EventScript_PCTurnOn

PlayersHouse_2F_EventScript_ShowPaletteMenu::
	message LittlerootTown_BrendansHouse_2F_Text_SelectPalette
	waitmessage
	multichoice 0, 0, MULTI_PALETTE_CHOICE, FALSE
	switch VAR_RESULT
	case 0, PlayersHouse_2F_EventScript_SelectDefaultPalette
	case 1, PlayersHouse_2F_EventScript_SelectBluePalette
	case 2, PlayersHouse_2F_EventScript_SelectYellowPalette
	case 3, PlayersHouse_2F_EventScript_SelectOrangePalette
	case 4, PlayersHouse_2F_EventScript_SelectCyanPalette
	case 5, PlayersHouse_2F_EventScript_SelectPinkPalette
	case 6, PlayersHouse_2F_EventScript_SelectSilverPalette
	case 7, PlayersHouse_2F_EventScript_SelectGoldPalette
	case 8, PlayersHouse_2F_EventScript_SelectPeriwinklePalette
	case 9, PlayersHouse_2F_EventScript_SelectForestPalette
	case 10, PlayersHouse_2F_EventScript_SelectSkyBluePalette
	return

PlayersHouse_2F_EventScript_SelectDefaultPalette::
	setvar VAR_PLAYER_PALETTE_CHOICE, 0
	msgbox LittlerootTown_BrendansHouse_2F_Text_PaletteSelectedDefault, MSGBOX_DEFAULT
	return

PlayersHouse_2F_EventScript_SelectBluePalette::
	setvar VAR_PLAYER_PALETTE_CHOICE, 1
	msgbox LittlerootTown_BrendansHouse_2F_Text_PaletteSelectedBlue, MSGBOX_DEFAULT
	return

PlayersHouse_2F_EventScript_SelectYellowPalette::
	setvar VAR_PLAYER_PALETTE_CHOICE, 2
	msgbox LittlerootTown_BrendansHouse_2F_Text_PaletteSelectedYellow, MSGBOX_DEFAULT
	return

PlayersHouse_2F_EventScript_SelectOrangePalette::
	setvar VAR_PLAYER_PALETTE_CHOICE, 3
	msgbox LittlerootTown_BrendansHouse_2F_Text_PaletteSelectedOrange, MSGBOX_DEFAULT
	return

PlayersHouse_2F_EventScript_SelectCyanPalette::
	setvar VAR_PLAYER_PALETTE_CHOICE, 4
	msgbox LittlerootTown_BrendansHouse_2F_Text_PaletteSelectedCyan, MSGBOX_DEFAULT
	return

PlayersHouse_2F_EventScript_SelectPinkPalette::
	setvar VAR_PLAYER_PALETTE_CHOICE, 5
	msgbox LittlerootTown_BrendansHouse_2F_Text_PaletteSelectedPink, MSGBOX_DEFAULT
	return

PlayersHouse_2F_EventScript_SelectSilverPalette::
	setvar VAR_PLAYER_PALETTE_CHOICE, 6
	msgbox LittlerootTown_BrendansHouse_2F_Text_PaletteSelectedSilver, MSGBOX_DEFAULT
	return

PlayersHouse_2F_EventScript_SelectGoldPalette::
	setvar VAR_PLAYER_PALETTE_CHOICE, 7
	msgbox LittlerootTown_BrendansHouse_2F_Text_PaletteSelectedGold, MSGBOX_DEFAULT
	return

PlayersHouse_2F_EventScript_SelectPeriwinklePalette::
	setvar VAR_PLAYER_PALETTE_CHOICE, 8
	msgbox LittlerootTown_BrendansHouse_2F_Text_PaletteSelectedPeriwinkle, MSGBOX_DEFAULT
	return

PlayersHouse_2F_EventScript_SelectForestPalette::
	setvar VAR_PLAYER_PALETTE_CHOICE, 9
	msgbox LittlerootTown_BrendansHouse_2F_Text_PaletteSelectedForest, MSGBOX_DEFAULT
	return

PlayersHouse_2F_EventScript_SelectSkyBluePalette::
	setvar VAR_PLAYER_PALETTE_CHOICE, 10
	msgbox LittlerootTown_BrendansHouse_2F_Text_PaletteSelectedSkyBlue, MSGBOX_DEFAULT
	return

PlayersHouse_2F_EventScript_PCTurnOn::
	callnative UpdatePlayerPalette
	playse SE_PC_OFF
	special DoPCTurnOffEffect
	releaseall
	end

LittlerootTown_BrendansHouse_2F_EventScript_TurnOffPlayerPC::
	setvar VAR_0x8004, PC_LOCATION_BRENDANS_HOUSE
	playse SE_PC_OFF
	special DoPCTurnOffEffect
	releaseall
	end

LittlerootTown_BrendansHouse_2F_EventScript_CheckRivalsPC::
	msgbox gText_PokemonTrainerSchoolEmail, MSGBOX_DEFAULT
	releaseall
	end

PlayersHouse_2F_EventScript_Notebook::
	lock
	call EventScript_ChooseGiftPokemon
	release
	end

PlayersHouse_2F_EventScript_GameCube::
	msgbox PlayersHouse_2F_Text_ItsAGameCube, MSGBOX_SIGN
	end

PlayersHouse_2F_EventScript_Fossil::
	goto_if_set FLAG_UNUSED_0x264, PlayersHouse_2F_EventScript_Receive_Fossil
	end

PlayersHouse_2F_EventScript_Receive_Fossil::
	msgbox PlayersHouse_2F_Text_DustyFossil, MSGBOX_SIGN
	randomelement SPECIES_OMANYTE, SPECIES_KABUTO, SPECIES_ANORITH, SPECIES_LILEEP, SPECIES_CRANIDOS, SPECIES_SHIELDON, SPECIES_ARCHEN, SPECIES_TIRTOUGA, SPECIES_TYRUNT, SPECIES_AMAURA
	givemon VAR_RESULT, 15, ITEM_NONE
	playfanfare MUS_OBTAIN_ITEM
	msgbox PlayersHouse_2F_Text_AncientPokemon
	waitmessage
	waitfanfare
	clearflag FLAG_UNUSED_0x264
	releaseall
	end

PlayersHouse_2F_Text_HowDoYouLikeYourRoom:
	.string "MOM: {PLAYER}, how do you like your\n"
	.string "new room?\p"
	.string "Good! Everything's put away neatly!\p"
	.string "They finished moving everything in\n"
	.string "downstairs, too.\p"
	.string "POKéMON movers are so convenient!\p"
	.string "Oh, you should make sure that\n"
	.string "everything's all there on your desk.$"

PlayersHouse_2F_Text_Notebook:
	.string "{PLAYER} flipped open the notebook.\p"
	.string "ADVENTURE RULE NO. 1\n"
	.string "Open the MENU with START.\p"
	.string "ADVENTURE RULE NO. 2\n"
	.string "Record your progress with SAVE.\p"
	.string "The remaining pages are blank…$"

Common_Text_LookCloserAtMap:
	.string "{PLAYER} took a closer look at the\n"
	.string "HOENN region map.$"

PlayersHouse_2F_Text_ItsAGameCube:
	.string "It's a Nintendo GameCube.\p"
	.string "It's currently playing\n"
	.string "POKéMON EMERALD BLITZ v8.6.$"

PlayersHouse_2F_Text_DustyFossil:
	.string "{PLAYER} looked under the bed…\p"
	.string "Oh, what's this?\n"
	.string "{PLAYER} pulled out a dusty old fossil.\p"
	.string "Ah! It's reviving itself!$"

PlayersHouse_2F_Text_AncientPokemon:
	.string "{PLAYER} received an ancient POKéMON!$"

LittlerootTown_BrendansHouse_2F_Text_PaletteChoice:
	.string "Would you like to customize your\n"
	.string "player palette?$"

LittlerootTown_BrendansHouse_2F_Text_SelectPalette:
	.string "Select a palette:$"

LittlerootTown_BrendansHouse_2F_Text_PaletteSelectedDefault:
	.string "Palette set to Default.$"

LittlerootTown_BrendansHouse_2F_Text_PaletteSelectedBlue:
	.string "Palette set to Purple.$"

LittlerootTown_BrendansHouse_2F_Text_PaletteSelectedYellow:
	.string "Palette set to Yellow.$"

LittlerootTown_BrendansHouse_2F_Text_PaletteSelectedOrange:
	.string "Palette set to Orange.$"

LittlerootTown_BrendansHouse_2F_Text_PaletteSelectedCyan:
	.string "Palette set to Cyan.$"

LittlerootTown_BrendansHouse_2F_Text_PaletteSelectedPink:
	.string "Palette set to Pink.$"

LittlerootTown_BrendansHouse_2F_Text_PaletteSelectedSilver:
	.string "Palette set to Silver.$"

LittlerootTown_BrendansHouse_2F_Text_PaletteSelectedGold:
	.string "Palette set to Gold.$"

LittlerootTown_BrendansHouse_2F_Text_PaletteSelectedPeriwinkle:
	.string "Palette set to Blue.$"

LittlerootTown_BrendansHouse_2F_Text_PaletteSelectedForest:
	.string "Palette set to Forest.$"

LittlerootTown_BrendansHouse_2F_Text_PaletteSelectedSkyBlue:
	.string "Palette set to Sky.$"

PlayersHouse_1F_Text_ReceivedEgg:
	.string "{PLAYER} received an egg!$"

LittlerootTown_BrendansHouse_2F_EventScript_GrandPrixMessage::
	msgbox gText_GrandPrixMessage, MSGBOX_SIGN
	end